export enum ProductCategory {
  SOFAS = 'SOFAS',
  CHAIRS = 'CHAIRS',
  TABLES = 'TABLES',
  BEDS = 'BEDS',
  WARDROBES = 'WARDROBES',
  CABINETS = 'CABINETS',
  SHELVES = 'SHELVES',
  DECORATION = 'DECORATION',
  OTHERS = 'OTHERS',
}
