POST http://localhost:5001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "tony",
  "password": "Tonyrmit@2301"
}


GET http://localhost:5001/api/customers/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFkMDI3ZTM0ZGQ4ZjgxM2QxMTk5NmYiLCJ1c2VybmFtZSI6InRvbnkiLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTYyMDcyMzgsImV4cCI6MTc1NjgxMjAzOH0.AYxl5AReb_C1VmVNcSnqMNcNubLSBWNdLahx_h2xZOI


GET http://localhost:5001/api/customers/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFkMDI3ZTM0ZGQ4ZjgxM2QxMTk5NmYiLCJ1c2VybmFtZSI6InRvbnkiLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTYyMDcyMzgsImV4cCI6MTc1NjgxMjAzOH0.AYxl5AReb_C1VmVNcSnqMNcNubLSBWNdLahx_h2xZOI

GET http://localhost:5001/api/customers/stores/68ab616fc9699e4bca89a714
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFkMDI3ZTM0ZGQ4ZjgxM2QxMTk5NmYiLCJ1c2VybmFtZSI6InRvbnkiLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTYyMDcyMzgsImV4cCI6MTc1NjgxMjAzOH0.AYxl5AReb_C1VmVNcSnqMNcNubLSBWNdLahx_h2xZOI


### Add item to cart
POST http://localhost:5001/api/customers/cart HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFkMDI3ZTM0ZGQ4ZjgxM2QxMTk5NmYiLCJ1c2VybmFtZSI6InRvbnkiLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTYyMDcyMzgsImV4cCI6MTc1NjgxMjAzOH0.AYxl5AReb_C1VmVNcSnqMNcNubLSBWNdLahx_h2xZOI

{
  "itemId": "68a6eea9748d1da6d1719916",
  "quantity": 2
}

PUT http://localhost:5001/api/customers/cart HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFkMDI3ZTM0ZGQ4ZjgxM2QxMTk5NmYiLCJ1c2VybmFtZSI6InRvbnkiLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTYyMDcyMzgsImV4cCI6MTc1NjgxMjAzOH0.AYxl5AReb_C1VmVNcSnqMNcNubLSBWNdLahx_h2xZOI

{
  "itemId": "68a6eea9748d1da6d1719916",
  "quantity": -1
}

DELETE http://localhost:5001/api/customers/cart/68a6eea9748d1da6d1719916 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFkMDI3ZTM0ZGQ4ZjgxM2QxMTk5NmYiLCJ1c2VybmFtZSI6InRvbnkiLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTYyMDcyMzgsImV4cCI6MTc1NjgxMjAzOH0.AYxl5AReb_C1VmVNcSnqMNcNubLSBWNdLahx_h2xZOI


POST http://localhost:5001/api/customers/orders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFkMDI3ZTM0ZGQ4ZjgxM2QxMTk5NmYiLCJ1c2VybmFtZSI6InRvbnkiLCJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3NTYyMDcyMzgsImV4cCI6MTc1NjgxMjAzOH0.AYxl5AReb_C1VmVNcSnqMNcNubLSBWNdLahx_h2xZOI
